name: xxx
description: A new flutter module project.
dependencies:
  http: ^1.0.0 # 確保為最新的 Null Safety 版本
  date_format: ^2.0.3  # 確保為最新的 Null Safety 版本
environment:
  sdk: ">=2.12.0 <4.0.0" # 支持 Null Safety